services:
  - type: web
    name: gravador-audio-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    disk:
      name: audio-storage
      mountPath: /app/uploads
      sizeGB: 1
